CREATE TABLE place
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    code      VARCHAR(255)                            NOT NULL,
    capacity  INTEGER                                 NOT NULL,
    available BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_place PRIMARY KEY (id)
);

ALTER TABLE place
    ADD CONSTRAINT uc_place_code UNIQUE (code);