CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    starts_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finishes_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    place_id    BIGINT,
    description VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_PLACE FOREIGN KEY (place_id) REFERENCES place (id);
