ALTER TABLE event
  ALTER COLUMN starts_at   TYPE TIMESTAMP(0) WITHOUT TIME ZONE,
  ALTER COLUMN finishes_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE,
  ALTER COLUMN created_at  TYPE TIMESTAMP(0) WITHOUT TIME ZONE,
  ALTER COLUMN updated_at  TYPE TIMESTAMP(0) WITHOUT TIME ZONE;